version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ortowhave_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ortowhave
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ortowhave
      MYSQL_PASSWORD: ortowhave
    volumes:
      - ortowhave_data:/var/lib/mysql

volumes:
  ortowhave_data: 