server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: orthowave-backend
  datasource:
    url: jdbc:mysql://localhost:3307/ortowhave?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Hikennoace.v2510
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: noresetowc@hotmail.com
    password: xdothdfawkulljjz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  thymeleaf:
    cache: false

jwt:
  secret: ${JWT_SECRET:your-secret-key-here}
  expiration: 86400000 # 24 horas en milisegundos

cors:
  allowed-origins:
    - http://localhost:3000
    - https://orthowave-colombia.vercel.app

logging:
  level:
    org.springframework.security: DEBUG
    com.orthowave.backend: DEBUG 